{% set name = "morefs" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morefs-{{ version }}.tar.gz
  sha256: 6119d12c975d1a7e89d0837c99cd5fc82e7e392e74ecb041634ab394d137f8e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=48
    - setuptools-scm >=6.3.1
    - pip
  run:
    - python >=3.8
    - fsspec

test:
  imports:
    - morefs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iterative/morefs
  summary: A collection of self-contained fsspec-based filesystems
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/iterative/morefs
  doc_url: https://github.com/iterative/morefs/blob/main/README.rst

extra:
  recipe-maintainers:
    - xylar
